```{r data generation, echo = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=100)
mu = sample(seq(30,70,5),1)
sigma = sample(2:10,1)
n = c(25,100,400)
totlb = n*mu-2*sqrt(n)*sigma
totub = n*mu+2*sqrt(n)*sigma
avelb = mu-2*sigma/sqrt(n)
aveub = mu+2*sigma/sqrt(n)
```

Question
========

### Population

Random variable $X$ has mean $\mu=`r mu`$ and standard deviation $\sigma=`r sigma`$. 

### Interval of typical measurements 

Let the interval of typical measurements be defined as having lower bound $\mu-2\sigma$ and upper bound $\mu+2\sigma$.
$$\text{interval of typical measurements} = (\mu-2\sigma, \, \mu+2\sigma)$$

Calculate the lower bound of the interval of typical measurements.
##ANSWER1##

Calculate the upper bound of the interval of typical measurements.
##ANSWER2##

### Interval of typical totals

Let the interval of typical totals be defined as having lower bound $n\mu-2\sigma\sqrt{n}$ and upper bound $n\mu+2\sigma\sqrt{n}$.
$$\text{interval of typical totals} = \left(n\mu-2\sigma\sqrt{n}, \, n\mu+2\sigma\sqrt{n}\right)$$

For the listed values of $n$, determine the bounds.

| $n$ | _ lower bound of typical totals _ | _ upper bound of typical totals _ |
|:---:|:---:|:---:|
| 25  | ##ANSWER3## | ##ANSWER4## |
| 100  | ##ANSWER5## | ##ANSWER6## |
| 400  | ##ANSWER7## | ##ANSWER8## |

### Interval of typical averages

Let the interval of typical averages be defined as having lower bound $\mu-\frac{2\sigma}{\sqrt{n}}$ and upper bound $\mu+\frac{2\sigma}{\sqrt{n}}$.

$$\text{interval of typical averages} = \left(\mu-\frac{2\sigma}{\sqrt{n}}, \, \mu+\frac{2\sigma}{\sqrt{n}}\right)$$
For the listed values of $n$, determine the bounds.

| $n$ | _ lower bound of typical averages _ | _ upper bound of typical averages _ |
|:---:|:---:|:---:|
| 25  | ##ANSWER9## | ##ANSWER10## |
| 100  | ##ANSWER11## | ##ANSWER12## |
| 400  | ##ANSWER13## | ##ANSWER14## |


Solution
========

### Interval of typical measurements 

$$\text{lower bound} = `r mu-2*sigma` $$
$$\text{upper bound} = `r mu+2*sigma` $$

### Interval of typical totals

| $n$ | _ lower bound of typical totals _ | _ upper bound of typical totals _ |
|:---:|:---:|:---:|
| 25  | `r totlb[1]` | `r totub[1]` |
| 100  | `r totlb[2]` | `r totub[2]` |
| 400  | `r totlb[3]` | `r totub[3]` |

### Interval of typical averages

| $n$ | _ lower bound of typical averages _ | _ upper bound of typical averages _ |
|:---:|:---:|:---:|
| 25  | `r avelb[1]` | `r aveub[1]` |
| 100  | `r avelb[2]` | `r aveub[2]` |
| 400  | `r avelb[3]` | `r aveub[3]` |


Meta-information
================
extype: cloze
exclozetype: num|num|num|num|num|num|num|num|num|num|num|num|num|num
exsolution: `r mu-2*sigma`|`r mu+2*sigma`|`r totlb[1]`|`r totub[1]`|`r totlb[2]`|`r totub[2]`|`r totlb[3]`|`r totub[3]`|`r avelb[1]`|`r aveub[1]`|`r avelb[2]`|`r aveub[2]`|`r avelb[3]`|`r aveub[3]`
exname: intervals typical measurements, means, totals
extol: 0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1|0.1
exextra[numwidth,numeric]: 6
exextra[stringwidth,numeric]: 6
