```{r,data,generation,echo=FALSE,results="hide"}
types = c("Bell","Uniform","Bimodal","Right-skew","Left-skew")

n = 2000
beta1 = c(3,1,0.5,0.7,1.4)
beta2 = c(3,1,0.5,1.4,0.7)

bell = rbeta(n,beta1[1],beta2[1])
uniform = rbeta(n,beta1[2],beta2[2])
bimodal = rbeta(n,beta1[3],beta2[3])
right_skew = rbeta(n,beta1[4],beta2[4])
left_skew = rbeta(n,beta1[5],beta2[5])

data = data.frame(bell,uniform,bimodal,right_skew,left_skew)

ord = sample(1:5)
ord2 = sample(1:5)
```


Question
========

Match the five histograms with their appropriate description.

```{r echo=F,fig.width=8,fig.height=5}
par(mfrow=c(2,3))
for(j in 1:5){
  par(mar=c(2,1,3,1))
  i = ord[j]
  hist(data[,i],axes=F,xlim=c(0,1),main=paste0("distribution ",j),col=rgb(0.9,0.7,0.7))
  box("figure")
}
```
\

Answerlist
--------
* `r types[ord2[1]]` (Enter an integer between 1 and 5)
* `r types[ord2[2]]` (Enter an integer between 1 and 5)
* `r types[ord2[3]]` (Enter an integer between 1 and 5)
* `r types[ord2[4]]` (Enter an integer between 1 and 5)
* `r types[ord2[5]]` (Enter an integer between 1 and 5)



Solution
========

[video](https://vimeo.com/531905117){target="_blank"}

This is definitional.


Answerlist
--------
* `r which(ord==ord2[1])`
* `r which(ord==ord2[2])`
* `r which(ord==ord2[3])`
* `r which(ord==ord2[4])`
* `r which(ord==ord2[5])`



Meta-information
================
extype: cloze
exclozetype: num|num|num|num|num
exsolution: `r which(ord==ord2[1])`|`r which(ord==ord2[2])`|`r which(ord==ord2[3])`|`r which(ord==ord2[4])`|`r which(ord==ord2[5])`
exname: identify_shapes
extol: 0
exextra[numwidth]: 999.999
