```{r data generation, echo = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=100)

while(T){
  mu0 = round(runif(1,10,100),1)
  sig0 = round(runif(1,mu0/6,mu0/3),1)
  n = sample(20:100,1)
  
  pval = 0.05+runif(1,0.01,0.04)*sample(c(-1,1),1)
  
  lt = pval/2
  zl = round(qnorm(lt),2)
  
  z = zl*sample(c(-1,1),1)
  
  xbar = round(mu0+sig0/sqrt(n)*z,2)
  z = (xbar-mu0)/(sig0/sqrt(n))
  zlo = floor(z*100)/100
  zhi = ceiling(z*100)/100
  
  lt = pnorm(-abs(z))
  pval = 2*lt
  
  ltlo = round(pnorm(-abs(zlo)),4)
  lthi = round(pnorm(-abs(zhi)),4)
  pvallo = 2*ltlo
  pvalhi = 2*lthi
  
  if((pvallo < 0.05)==(pvalhi < 0.05) & (pvallo > 0.05)==(pvalhi > 0.05)){
    break
  }
}

tol = max(abs(pvalhi-pvallo),0.001)

if(pval < 0.05){
  ans2 = "10"
} else {
  ans2 = "01"
}

```

Question
========

A scientist is investigating whether a chemical may effect the growth of an organism. Under the control conditions (no chemical), the organism grows to a mean mass of $\mu_0 = `r mu0`$ grams with a standard deviation of $\sigma_0 =`r sig0`$ grams. These values are known precisely because the organism has been grown under control conditions many many times.

The scientist has only grown the organism under experimental conditions (with chemical) $n=`r n`$ times. In that sample, the masses have a mean $\bar{x}=`r xbar`$.

The scientist wonders if this sample mean is significantly different from $\mu_0$. To do this, the scientist will determine the $p$-value. The $p$-value represents the probability of getting a sample mean as far (or farther) from $\mu_0$ due to chance alone.
$$p\text{-value} ~=~ P\left(\big|Z\big| > \frac{\big|\bar{x}-\mu_0\big|}{\sigma_0/\sqrt{n}} \right) $$

It is common to compare the $p$-value to 0.05.

* If $p\text{-value} < 0.05$ then "significant"
* If $p\text{-value} \ge 0.05$ then "not significant"


Answerlist
--------
* Determine the $p$-value.
* The difference is significant. The chemical seems to alter the growth of the organism.
* The difference is not significant. We don't know whether the chemical alters the growth of the organism.


Solution
========

We need to calculate the $p$-value.
$$\begin{aligned}
p\text{-value} &= P\left(\big|Z\big| > \frac{\big|\bar{x}-\mu_0\big|}{\sigma_0/\sqrt{n}} \right) \\\\
&= P\left(\big|Z\big| > \frac{\big|`r xbar`-`r mu0`\big|}{`r sig0`/\sqrt{`r n`}} \right) \\\\
&= P\left(\big|Z\big| > `r abs(xbar-mu0)/sig0*sqrt(n)` \right) \\\\
&= `r pval`
\end{aligned}$$

Of course you could have rounded the $z$ score. Either of the following will also get credit.

$$p\text{-value} ~=~ \left(\big|Z\big| > `r zlo` \right) ~=~ `r pvallo`$$
$$p\text{-value} ~=~ \left(\big|Z\big| > `r zhi` \right) ~=~ `r pvalhi`$$

Answerlist
--------
* `r pval`
* `r pval<0.05`
* `r pval>=0.05`


Meta-information
================
extype: cloze
exsolution: `r pval`|`r ans2`
exclozetype: num|schoice
exname: basic hypothesis test
extol: `r tol`

