```{r data generation, echo = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=100)


mag = sample((-1):2,1)
s = round(runif(1,1,10),1)*10^mag
mag2 = sample(2:4,1)
n = round(runif(1,1,10),1)*10^mag2
me = signif(2*s/sqrt(n),2)
n = round((2*s/me)^2)

#ME = (2*s)/sqrt(n)
```

Question
========

We can approximate a 95% confidence interval (where the 95% refers to the confidence level: how frequently these intervals straddle the population mean) by using $\bar{x}\pm \frac{2 s}{\sqrt{n}}$.
$$\text{lower boundary} = \bar{x}-\frac{2s}{\sqrt{n}}$$
$$\text{upper boundary} = \bar{x}+\frac{2s}{\sqrt{n}}$$
where $\bar{x}$ is the sample mean, $s$ is the sample standard deviation, and $n$ is the sample size. The 2 comes from the fact that 95% of normal measurements land within 2 standard deviations from the mean.

The quantity that we subtract from or add to the sample mean is called **the margin of error**.
$$\text{margin of error} = \frac{2s}{\sqrt{n}}$$

When using a confidence level of 0.95, knowing $s$ will be approximately `r s`, and wanting the margin of error to be approximately `r me`, how large does the sample size need to be?

You can round your answer to two significant digits.



Solution
========

Do some algebra.
$$ME = \frac{2s}{\sqrt{n}} $$
Multiply both sides by $\sqrt{n}$.
$$ME\sqrt{n} = 2s $$
Divide both sides by $ME$.
$$\sqrt{n} = \frac{2s}{ME} $$
Square both sides.
$$n  = \left(\frac{2s}{ME}\right)^2$$
Plug in numbers.
$$n  = \left(\frac{(2)(`r s`)}{`r me`}\right)^2$$
Evaluate.
$$n  = `r n`$$

The tolerance is $\pm `r 10^(mag2-1)`$, so you can round to 2 significant digits, giving $n=`r signif(n,2)`$.


Meta-information
================
extype: num
exsolution: `r n`
exname: n from ME
extol: `r 10^(mag2-1)`

