```{r,data,generation,echo=FALSE,results="hide",fig.show='hide'}
mu = round(runif(1,20,80),1)
sig = round(runif(1,2,10),1)

lb = mu-2*sig
ub = mu+2*sig
```


Question
========

### Background

Sometimes a population is well characterized. In this case we know its mean and standard deviation. We use greek letters $\mu$ ("mu") and $\sigma$ ("sigma") when describing the population (instead of the $\bar{x}$ ("xbar") and $s$ used for sample mean and sample standard deviation).
$$\mu = \text{population mean} $$
$$\sigma = \text{population standard deviation} $$

When measuring individuals from a population, we expect most measurements to be within the *interval of typical measurements*. We will define the interval of typical measurements (using [interval notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals){target="blank"}):
$$\text{interval of typical measurements} = (\mu-2\sigma,\,\mu+2\sigma) $$
In other words, we expect we expect most measurements to be between two bounds.
$$\text{lower bound of interval of typical measurements} = \mu-2\sigma $$
$$\text{upper bound of interval of typical measurements} = \mu+2\sigma $$

### Actual Question

A population of lizards has a mean length of $\mu = `r sprintf("%.1f",mu)`$ cm and a standard deviation of $\sigma=`r sprintf("%.1f",sig)`$ cm. Determine the interval of typical measurements.

Answerlist
--------
* Determine the lower bound of the interval of typical measurements.
* Determine the upper bound of the interval of typical measurements.


Solution
========

You need to use the formulas. Remember your [order of operations](https://en.wikipedia.org/wiki/Order_of_operations){target="blank"}!

Answerlist
--------
* Use the formula. $\mu-2\sigma = `r mu` - 2(`r sig`) = `r mu-2*sig`$
* Use the formula. $\mu+2\sigma = `r mu` + 2(`r sig`) = `r mu+2*sig`$


Meta-information
================
extype: cloze
exclozetype: num|num
exsolution: `r mu-2*sig`|`r mu+2*sig`
exname: get_interval_of_typical_measurements
extol: 0
exextra[numwidth]: 999.999