```{r data generation, echo = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=100)

phat = round(runif(1,0.02,0.98),2)
mag2 = sample(2:4,1)
n = round(runif(1,1,10),1)*10^mag2
me = signif(2*sqrt(phat*(1-phat))/sqrt(n),2)
n = round(4*phat*(1-phat)/me^2)

```

Question
========

We can approximate a 95% confidence interval of a **proportion** (where the 95% refers to how frequently these intervals straddle the population proportion) by using $\hat{p} \pm \frac{2 \sqrt{\hat{p}(1-\hat{p})}}{\sqrt{n}}$.
$$\text{lower boundary} = \hat{p} - \frac{2 \sqrt{\hat{p}(1-\hat{p})}}{\sqrt{n}}$$
$$\text{upper boundary} = \hat{p} + \frac{2 \sqrt{\hat{p}(1-\hat{p})}}{\sqrt{n}}$$
where $\hat{p}$ is the sample proportion and $n$ is the sample size. The 2 comes from the fact that 95% of normal measurements land within 2 standard deviations from the mean.

The quantity that we subtract from or add to the sample proportion is called **the margin of error**.
$$\text{margin of error} = \frac{2 \sqrt{\hat{p}(1-\hat{p})}}{\sqrt{n}}$$

If we know $\hat{p}$ will be approximately `r phat`, and we want the margin of error to be approximately `r me`, then how large does the sample size need to be?

You can round your answer to two significant digits.



Solution
========

Do some algebra.
$$ME = \frac{2 \sqrt{\hat{p}(1-\hat{p})}}{\sqrt{n}} $$
Multiply both sides by $\sqrt{n}$.
$$ME\sqrt{n} = 2\sqrt{\hat{p}(1-\hat{p})} $$
Divide both sides by $ME$.
$$\sqrt{n} = \frac{2\sqrt{\hat{p}(1-\hat{p})}}{ME} $$
Square both sides.
$$n  = \left(\frac{2\sqrt{\hat{p}(1-\hat{p})}}{ME}\right)^2$$
Simplify.
$$n  = \frac{4\hat{p}(1-\hat{p})}{ME^2}$$

Plug in numbers.
$$n  = \frac{4(`r phat`)(`r 1-phat`)}{`r me`^2}$$
Evaluate.
$$n  = `r n`$$

The tolerance is $\pm `r 10^(mag2-1)`$, so you can round to 2 significant digits, giving $n=`r signif(n,2)`$.


Meta-information
================
extype: num
exsolution: `r n`
exname: n from ME prop
extol: `r 10^(mag2-1)`

